name: Build and validate

on: push

jobs:
  build:
    strategy:
      fail-fast: false
      matrix:
        include:
          - os: ubuntu-latest
            install-script: sudo apt-get install make automake libtool libtool-bin autoconf doxygen gfortran g++ 
          - os: macos-latest
            install-script: brew install make automake libtool autoconf doxygen gfortran

    runs-on: ${{ matrix.os }}
    steps:
    - uses: actions/checkout@v2
    - name: Install requirements
      run: ${{ matrix.install-script }}
    - name: Build
      run: ./non_interactive_autogen.sh -s
    - name: Validate
      run: make check -k -s
    - name: Upload validation log file
      if: ${{ always() }}
      uses: actions/upload-artifact@v2
      with:
        name: Validation log file
        path: ./validation.log
